import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import BgGrid from "@/components/atoms/BgGrid";
import Footer from "@/components/organisms/Footer";
import Nav from "@/components/organisms/Nav";

const whyte = localFont({
  src: "../../public/fonts/ABCWhyteVariable-Trial.woff2",
  variable: "--font-whyte",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${whyte.variable} font-sans antialiased relative`}>
        <Nav />
        <main>{children}</main>
        <Footer />
        <BgGrid />
      </body>
    </html>
  );
}
